version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2181'
  kafka:
    image: wurstmeister/kafka
    ports:
      - '9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
    volumes:
      - /var/run/docker.sock
  incidashboardi1a:
    image: 'arquisoft/incidashboardi1a:master'
    ports:
      - '8082'
    depends_on:
      - kafka
  incimanageri1a:
    image: 'arquisoft/incimanageri1a:master'
    ports:
      - '8081'
    depends_on:
      - kafka